### ISSUE TITLE
File Servers

### ISSUE THREAD

**Issue by Deepnerd** [cypherbits/nullupload#1]
Hi @cypherbits can you explain me how to add remote file servers when my local file storage full? 

Also it would be better how to install this properly on a web server.

i like to check this script but i don't know how to run this on my localhost. 
(windows 7)     (currently using xampp)

And i like to test this on ubuntu 18.04x64 vps. can you please kindly guide me how to install and use this script properly in a secure way. Thank you very much for your time that you spend to this project. best, up to date secure file sharing script i ever seen in github. keep up the good work! 
****good luck!****

**Comment by cypherbits** [comment]
Hi, what do you mean with remote file servers? Do you mean more vps or something to act as more storage for the main server? This is not implemented yet and I'm thinking about how to do it. I will adapt it to Object Storage things...

Btw, this project does not store the files encrypted. I didn't do it because it was very expensive, but with new PHP, maybe I can make an option if you are interested.

I will make a setup guide. Or even an automated php script....

The steps are just create a Mysql database, use the setup.sql file to create all data and tables.
Change the config.php file to set the database user and password.

I will do when I have free time.......

**Comment by Deepnerd** [comment]
Exactly, you understands me very well, thank you! waiting for the next update! Thank you.

**Comment by cypherbits** [comment]
Hi, did you try to install it manually?
do you need a file upload script soon for a real file hosting or it's just for testing?

**Comment by Deepnerd** [comment]
Hi, didn't try yet... Yeah i need file upload script for a real file hosting.

**Comment by cypherbits** [comment]
> Hi, didn't try yet... Yeah i need file upload script for a real file sharing like anonfiles.com.

Do you need to encrypt the files?

**Comment by Deepnerd** [comment]
Yeah if it's possible thats great. i need it to be 100% Privacy focused. 
I planned to use servers under GDPR.

**Comment by Deepnerd** [comment]
Hey i found this, hope this will help you. sorry i don't underestimate your skills. im just trying to help you to make files encrypted option. i just saw this but this script little bugged i guess.i hope you can get something from this. https://github.com/blackstar54/Encrypted-File-Sharing 

also i got some errors when i run that script.

When im going to upload file i got this error
****Warning: mkdir(): No such file or directory in C:\xampp\htdocs\functions\upload.php on line 7****

And when i clicked on download button i got these errors
****Notice: Undefined index: hash in C:\xampp\htdocs\download.php on line 3****
****Notice: Undefined index: dec_key in C:\xampp\htdocs\download.php on line 4****
****Warning: A non-numeric value encountered in C:\xampp\htdocs\includes\footer.php on line 7****

I don't know if this ok to posting this in here. i i done anything wrong my apologies.

**Comment by cypherbits** [comment]
That script seems recent, but it uses deprecated and obsolete cryptography PHP mcrypt...
